[project]
name = "better-auth-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "fastmcp>=2.14.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
    "modal>=1.3.0.post1",
]
